services:
  - type: web
    name: klpp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "true"
